# Generated by Django 4.1 on 2023-02-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
