# Generated by Django 4.1 on 2023-02-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
