# Generated by Django 4.1 on 2023-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
