# Generated by Django 4.1 on 2023-04-11 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0005_alter_movie_rank_alter_movie_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Top250Movies',
        ),
        migrations.AlterModelOptions(
            name='top250movies',
            options={'verbose_name_plural': 'Top 250 Movies'},
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('crew', models.CharField(max_length=200, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('liked', models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
