# Generated by Django 4.1 on 2023-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_rename_movie_top250movies_alter_top250movies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='top250movies',
            name='genre',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
