# Generated by Django 4.1 on 2023-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_top250movies_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='duration',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='plot',
            field=models.TextField(max_length=258, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='stars',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
