# Generated by Django 4.1 on 2023-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_remove_movies_rank_remove_movies_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.CharField(max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='top250movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
