# Generated by Django 4.1 on 2023-04-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0010_alter_movies_plot_alter_movies_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='liked',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.CreateModel(
            name='MoviesLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movies Liked',
            },
        ),
    ]
