# Generated by Django 4.1 on 2023-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_remove_movies_liked_movies_movie_id_moviesliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='top250movies',
            name='genre',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='top250movies',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
