# Generated by Django 4.1 on 2023-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_alter_movies_director_alter_movies_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='top250movies',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
