# Generated by Django 4.1 on 2023-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0013_alter_movies_rating_alter_top250movies_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('crew', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(max_length=10, null=True)),
                ('genre', models.CharField(max_length=127, null=True)),
                ('plot', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=127, null=True)),
                ('duration', models.CharField(max_length=127, null=True)),
                ('series_id', models.CharField(max_length=44, null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
    ]
