# Generated by Django 4.1 on 2023-04-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0014_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Series',
        ),
    ]
