# Generated by Django 4.1 on 2023-04-17 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('crew', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(max_length=10, null=True)),
                ('genre', models.CharField(max_length=127, null=True)),
                ('plot', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=127, null=True)),
                ('duration', models.CharField(max_length=127, null=True)),
                ('series_id', models.CharField(max_length=44, null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Top250Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('year', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('crew', models.CharField(max_length=200, null=True)),
                ('rating', models.FloatField(max_length=10, null=True)),
                ('genre', models.CharField(max_length=127, null=True)),
                ('rank', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Top 250 Series',
            },
        ),
        migrations.CreateModel(
            name='SeriesLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.series')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Series Liked',
            },
        ),
    ]
