# Generated by Django 4.1 on 2023-04-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='top250series',
            name='genre',
        ),
    ]
