# Generated by Django 4.1 on 2023-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_remove_series_genre_remove_top250series_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='top250series',
            name='ratingCount',
            field=models.IntegerField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='top250series',
            name='serie_id',
            field=models.CharField(max_length=44, null=True),
        ),
    ]
