# Generated by Django 4.1 on 2023-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0003_top250series_ratingcount_top250series_serie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesliked',
            old_name='movie_id',
            new_name='serie_id',
        ),
        migrations.AlterField(
            model_name='top250series',
            name='ratingCount',
            field=models.IntegerField(null=True),
        ),
    ]
