# Generated by Django 4.1 on 2023-04-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0004_rename_movie_id_seriesliked_serie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
